---
swagger: "2.0"
info:
  description: "This is a sample server language server.  You can find out more about\
    \     Swagger at [http://localhost:3000/api-docs](http://localhost:3000/api-docs)\
    \ or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample,\
    \ you can use the api key `special-key` to test the authorization     filters."
  version: "1.0.0"
  title: "Swagger Languages"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:3000"
basePath: "/"
tags:
- name: "language"
  description: "Everything about your languages"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
schemes:
- "https"
- "http"
paths:
  /languages:
    get:
      tags:
      - "language"
      summary: "Get languages"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Language"
  /languages/{name}:
    get:
      tags:
      - "language"
      summary: "Get language by name"
      parameters:
      - name: "name"
        in: "path"
        description: "name of language"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Language"
  
securityDefinitions:
  petstore_auth:
    type: "oauth2"
    authorizationUrl: "http://petstore.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:pets: "modify pets in your account"
      read:pets: "read your pets"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  Language:
    type: "object"
    properties:
      name: 
        type: "string"
  Tag:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
    xml:
      name: "Tag"
    example:
      name: "name"
      id: 1
  
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
    example:
      code: 0
      type: "type"
      message: "message"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
